{% set name = "fragmenstein" %}
{% set version = "1.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Fragmenstein-{{ version }}.tar.gz
  sha256: 1b68a11b77132afbf52b77e491e54963c925f9a83c85fcc5622b570f5b42cb89

build:
  entry_points:
    - fragmenstein=fragmenstein.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - requests >=2.27.1
    - numpy >=1.21.6
    - scipy >=1.7.3
    - pandas >=1.3.5
    - pebble >=4.6.3
    - rdkit >=2023.09.5
    - rdkit-to-params >=1.2.8
    - molecular-rectifier >=1.0.1
    - singledispatchmethod >=1.0
    - typing_extensions >=4.8.0
    - matplotlib-base >=3.5.2
    - smallworld-api >=1.1
    - sqlitedict >=2.0.0
    - pandera >=0.17.2
    - pandarallel >=1.6.5
    - pyyaml >=6.0

test:
  imports:
    - fragmenstein
  commands:
    - pip check
    - fragmenstein --help
  requires:
    - pip

about:
  home: https://github.com/matteoferla/Fragmenstein
  summary: Merging, linking and placing compounds by stitching them together like a reanimated corpse
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
